FROM node:alpine

RUN mkdir -p /srv/app/reactlearn-client
WORKDIR /srv/app/reactlearn-client

COPY package.json /srv/app/reactlearn-client
COPY package-lock.json /srv-app/reactlearn-client

RUN npm install --silent
RUN npm install react-scripts -g --silent

COPY . /srv/app/reactlearn-client

CMD [ "npm", "start" ]